---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
env:
  matrix:
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7


install:
  - python3 -m pip install molecule
  - python3 -m pip install docker
  - python3 -m pip install ansible-lint
  # - python3 -m pip install required driver (e.g. docker, shade, boto, apache-libcloud)
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:  
      - secure: Pe3YQzxZcKRXS8RQOYeDCPdQz2aMo6D1PnIrmErIVD41M6zqtqaGaXOhHYfatC9TzERJS8zeI0XX1z9k02typ55N8UkY1yRZ19roXNtGsqLGLBDmTUxU5N70iAb3Jy2Y16kPENZI7UR/OxfCSLOpGasgLM0YYWDiFgS4yoyY4ZVVIQLIktJmCiO3nnBsp5IcWPlSbPahgzQP1QqHNoQhDxTH1JKxNubZzcOUjIKuBhC7Q16vUfjPgv6+aEUHsLpdLOC3XtmUpy+8x0nGqnkKSM9nl6JjYAwpvRdc1OfsCrE/jH4anpnJ79jglQU5TBv3oDwe4SfOOAjo9ShboNlm4DuCLX4KdzftFHDHy/Jy1uvq3X04EEmLriC1P/GiFOfpuOr0pOWMNY/HEswGVyA6c0Ntd6mNxD2KBWohlj6h1wJLqp2c1FOdxmNPWYS2PG71TWFiHppudP5cCQnPIVihY++xqh8D3xBnJL9WXTD+JxiTourh68ftSnBSxrfXDVcqcFRZw715QJE/z+iESm3OuunLgKX0xRCQgbbG1AVsQo3XnMkijv15tKKn82iInxij5cwYka28reh/Wo5XgzdXn8VmUaJwfBiohp9i5KVBIqAJGYshQpaNpuwSFEhsfZzOiBliAEvUYLslNarY8rvLgx9RG/pVC3h2s14T/Ll29Tc=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.