---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
env:
  matrix:
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7


install:
  - python3 -m pip install molecule
  - python3 -m pip install docker
  - python3 -m pip install ansible-lint
  # - python3 -m pip install required driver (e.g. docker, shade, boto, apache-libcloud)
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: siveyans:UXobOTHh49oRcImEpPLbw9O6