---
- name: Stat item.
  stat:
    path: "{{ apache_path }}/sites-available/{{ site_name }}.conf"
  register: st

- name: Generate site config
  template:
    src: site_config.j2
    dest: "{{ apache_path }}/sites-available/{{ site_name }}.conf"
    owner: "{{ apache_user }}"
    mode: 0600
    when: not st.stat.exists

- name: Create directories for web root
  file:
    path: "{{ document_root }}"
    state: directory
    mode: 0755
    owner: "{{ apache_user }}"

- name: Enable site config
  file:
    src: "{{ apache_path }}/sites-available/{{ site_name }}.conf"
    dest: "{{ apache_path }}/sites-enabled/{{ site_name }}.conf"
    state: link

- name: Create dummy site
  copy:
    src: dummy.html
    dest: "{{ document_root }}/index.html"
    mode: 0755
    owner: "{{ apache_user }}"
    group: "{{ apache_user }}"
  when: make_dummy_site

- name: Set permissions
  file:
    path: "{{ document_root }}"
    owner: "{{ apache_user }}"
    recurse: True
    mode: 0755