---
- name: Install apache2
  apt:
    name: apache2
    state: present

- name: Enable modules 
  apache2_module:
    state: present
    name: ssl

- name: Delete default apache site
  file:
    path: "{{ apache_path }}sites-enabled/000-default.conf"
    state: absent
  when: disable_default 