---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


# Setup/install tasks.
- include_tasks: "{{ ansible_os_family }}-apache-setup.yml"

# Configure server.
- include_tasks: "{{ ansible_os_family }}-apache-site.yml"

# Set up certificates.
- include_tasks: "ssl.yml"

- name: Start server
  systemd: 
    name: apache2
    state: started  


